### PR TITLE
Add support for connecting to unix sockets

### PR DESCRIPTION
**Pull request by m-harnish**

### CODE REVIEW

**Comment by Cylix** [comment]
Hi,

Thanks for your interest in cpp_redis!

However, I do not really understand the goal of that PR.
Technically, you should not have to check whether you are on unix or windows programmatically as the windows part of the code are not compiled unless you have define _WIN32 in your preprocessor directives.

Could it be possible that you have some issues concerning windows code compiled under unix?

For now, I can't really merge that code as it introduces unnecessary checks for unix/windows platform at runtime while it is currently already done at pre-processing time.

Best

**Comment by m-harnish** [comment]
Hello, thanks for the quick reply! Also, thanks for your work on cpp_redis :)

The goal of this PR is to allow unix domain socket connections to Redis in addition to regular TCP socket connections. So, for example, if Redis is listening on a unix socket at /tmp/redis.sock, cpp_redis can connect to that instead of localhost:6379.

To configure a unix vs TCP socket connection, the user would pass in a port of 0 and the unix socket location in place of the host param. For example: redis.connect("/tmp/redis.sock", 0, onDisconnect);

The actual unix vs Windows code is in each of the ifdef/else _WIN32  blocks. The only Windows code that ends up after the preprocessor runs is a check that throws an exception if someone tries configuring a unix socket on a Windows machine. This is so that I didn't have to change the signature of the setup_socket function depending on the type of build.

Please let me know if you have any other questions, or ideas on how to improve this!

Thanks, Marshall

**Comment by m-harnish** [comment]
Update: I just realized that I broke the Windows builds by not including an ifdef around the unix-specific code. Sorry about that!

I added the appropriate ifdef's and updated the PR.

Thanks, Marshall

**Comment by Cylix** [comment]
Interesting, didn't though about that use case.
The code is good, travis is happy and the feature is actually interesting: good to go!

Thanks a lot for your contribution :)

**Pull request merged**
