### PR TITLE
Add Visual C++ Build Config

### PR DESCRIPTION
**Pull request by zodiac403**
Hi Simon @Cylix,
thanks for the effort you put in this project.

The tool chain of my current project requires a MS Visual C++ compiler. I added project and solution files for MS Visual Studio 2017 for the current version:

- Visual Studio version **15** (a.k.a. 2017)
- VC++ tools version **15.0**
- Platform tool set **v141**

The project file assumes, that `tacopie` is checked out and compiled in directory `cpp_redis/tacopie`.

Are you interested in merging this into your work?

Any comments are welcome.

---
Before submitting the pull request, ensure that:

- [x] your feature works as expected and is tested
- [x] all tests pass on both your computer and the Travis
- *[N/A]* you have used the formatting tool

### CODE REVIEW

**Comment by Cylix** [comment]
Hi,

Thanks for your contribution, I really do appreciate :)
Before merging this, I have a few questions:
* is it common to publish .sln files to a repository (I will do my search on my side)
* What is the main advantage of it? You can technically regenerate it with CMake. So my guess is that it would make it easier for developers that do not have CMake installed?
* are sln files dependent to the VC++ versions they have been generated?
* if we merge it, what would be the typical steps for a new user to install the library from sratch (this is more for documentation purpose): DL cpp_redis > checkout tacopie > open tacopie sln > build tacopie > open cpp redis sln > build cpp redis? Or DL cpp_redis > checkout tacopie > open cpp redis sln > build cpp redis (which will build tacopie at the same time)?

Sorry for these questions, but that would help me to make it clearer for me :)

Thanks again for the time you spent on that contribution, I definitelly appreciate!

Best

**Comment by zodiac403** [comment]
Hi @Cylix,

thanks for the detailed answer. Probably my description was a litte short?

As far as I understood the CMake docs, you can auto-generate Visual Studio projects (VC(X)PROJ and SLN files) that work with the **Visual Studio IDE**, but still use the **CLANG compiler** to build the sources. It is not possible to generate projects  using CMAKE which build with  Microsoft's **MSBuild compiler** (how should they, that is a different tooling). This effort I had to do by hand. 

When a project supports compiling with MSBuild, it is quite common to keep the Visual Studio projects in the repo. For an example, take a look at libzmq's ["builds/msvc" directory](https://github.com/zeromq/libzmq/tree/master/builds/msvc). 

Unfortunately SLN and VC(X)PROJ files do depend on the tool version the were created with. For common cases Visual Studio can up-/downgrade the projects' versions, but often this causes some issues. Therefore it is not uncommon to provide different versions of project files (I only added support for the latest Visual Studio 2017).

How to build the project (assuming Visual Studio and MSBuild installed):

1. Clone or download cpp_redis
2. Checkout tacopie submodule
3. Open and build tacopie.sln in subfolder
4. Open and build cpp_redis.sln

If you prefer, we can add the tacopie project to cpp_redis.sln. This would make step 3 obsolete.

Do these answers help you? Feel free to post any further questions ;)

Best

**Comment by zodiac403** [comment]
Hi @Cylix 

just added the tacopie project to cpp_redis.sln. Now you can build both packages in the same solution: I think this is a more intuitive workflow.
Any updates on this PR?

Best

**Comment by Cylix** [comment]
Hey,

Sorry for the late reply!
I checked online and it seems it is pretty common to commit msvc directory on open source project repositories (even on big projects like googletest), so I'm perfectly fine with commiting it.

The thing I am a bit concerned about is that you mention you created these files by hand instead of CMake because CMake uses clang++ as the compiler of MSVC.
Do you have some example / ways to verify it?
I tried to double check and I think it just generates the project with MSBuild and seems like online people mention you have to do some specific customization to enable clang++ inside visual studio?

I just tried but couldn't make it work because my visual studio does not include the same build tool version, so I will need to double check how other projects deal with that (seems like googletest only publish one sln for example, so curious to know what is their process).
Additionally, I think I'd also look to find a way to make it work with clang generated files as it make it more maintainable when publishing a new release.

For now, what I have in mind is:
* I will check how do other projects handle build tool version and adjust the current files
* Then, I'll merge this PR
* In the meantime, I will also check what does CMake generates and integrate the generation of msvc files to the build/release process and draft a new PR

Thanks again for your contribution and really appreciate the idea. I would not have thought of doing that, but seems like it is common and make projects more accessible to windows developers!

Best

**Comment by zodiac403** [comment]
Hey @Cylix 

its been a while. Any updates on your research with comparable projects?

Just let me make my intentions a little clearer: If you want to edit your code in Visual Studio and compile your project with the CLang compiler, the existing solution works fine. If you want to integrate this library into a project built with Microsoft's Visual C++ compiler, imho the cleanest way would be to use this compiler (what I configured in the SLN and the VCXPROJ files).

I see your point of manual maintenance. You had to add new source files to VCXPROJ. Is this a big deal?

To continuously check, that the Visual Studio project is working, we could add a CI job for this one as well.

What are your thoughts?

Best

**Comment by Cylix** [comment]
Hey @zodiac403,

Sorry for the absence of activity.
I will update this PR to reflect the changes of source files that happened since this PR was opened, then I will merge it (as well as its tacopie equivalent).

There are still some points where I am unsure, but I guess we can merge it and see if some people report some issues in the future / get confused (and then improve based on feedbacks).

CI job for that is kind of tricky though: for now, I am based on Travis CI that does not support Windows build. I will check if others CI can be used for free and include such builds.

Thanks again for your contribution :)

**Comment by Cylix** [comment]
Good to go, sorry for the long time to process this one :)
Same as on tacopie: update with latest source files and target to 8.1/v140 to be more conservative.
Documentation will be added to the wiki.

Quite curious to see if this will make it easier for windows developer to build the library, but should be the case.

Thanks for your contribution!

**Comment by zodiac403** [comment]
Hi @Cylix 
thanks for the merge! I know, maintaining projects isn't the easiest work ;)

You are right, Travis and Windows don't go together well. Probably [Appveyor](https://www.appveyor.com/) could be an option: It offers similar features as Travis and runs jobs on Win. If you don't mind giving them access to your repo, I could work out a build recipe.

What do you think?

Best

**Comment by wenhuancai** [comment]
I would like to know how to build a project for VS2013, VS2012, VS2010. Can you teach me how to build a project? @zodiac403 @Cylix

**Comment by Cylix** [comment]
Hi @wenhuancai,

My MSVC version is VS2015, so I won't be able to test if the msvc15 solution works on these previous versions / provide one.

What happens if you try to open the msvc15/cpp_redis.sln with the VS2013 or earlier?

You might need to change the target OS and the build tools version to specify something matching what your visual studio supports.
To do so, opens the cpp_redis project properties. Then on the general option, you should be able to change the target version (technically windows 8.1), to something else. Same for the build tools version (technically v140).

Of course, if someone is willing to commit a version for an early visual version, would be happy to merge it.

Let me know if you have any other questions or troubles to build.

Best

**Pull request merged**
